[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.7.13"
volatile-register = "0.2.1"
spin = "0.9.3"
common = {path = "../common"}
